x-common-vars: &common-vars
  tty: true
  stdin_open: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: $RMW_IMPLEMENTATION
    ROS_DOMAIN_ID: $ROS_DOMAIN_ID
services:
    onboard-realsense:
        build:
            context: .
            target: realsense  
            args:
                USER: onboard
                LIBREALSENSE_VERSION: $LIBREALSENSE_VERSION
                REALSENSE_ROS_VERSION: $REALSENSE_ROS_VERSION
        <<: *common-vars
        image: vision-main:onboard-realsense
        container_name: onboard-realsense
        privileged: true
        volumes:
            - /dev:/dev
            - $LOCAL_WORKSPACE_FOLDER/config/dds-uri/cycloneDDS.xml:/tmp/cycloneDDS.xml
            - $LOCAL_WORKSPACE_FOLDER/packages/realsense-pkg:/home/onboard/vision-ws/src/realsense-ros
        device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
        command: bash
        profiles: ['camera']

    avoidance:
        build:
            context: .
            target: avoidance 
            args:
                USER: avoidance
        <<: *common-vars
        image: vision-main:avoidance
        container_name: avoidance
        volumes:
            - $LOCAL_WORKSPACE_FOLDER/packages/avoidance-pkg:/home/avoidance/vision-ws/src/avoidance-ros
        command: bash 
        profiles: ['avoid']

    feedback:
        build:
            context: .
            target: feedback 
            args:
                USER: feedback
        <<: *common-vars
        image: vision-main:feedback
        container_name: feedback
        volumes:
            - $LOCAL_WORKSPACE_FOLDER/packages/feedback-pkg:/home/feedback/vision-ws/src/feedback-ros
        command: bash
        profiles: ['feedback']