x-common-vars: &common-vars
  tty: true
  stdin_open: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: $RMW_IMPLEMENTATION
    ROS_DOMAIN_ID: $ROS_DOMAIN_ID
services:
    onboard-realsense:
        build:
            context: .
            target: realsense  
            args:
                USER: onboard
                LIBREALSENSE_VERSION: $LIBREALSENSE_VERSION
                REALSENSE_ROS_VERSION: $REALSENSE_ROS_VERSION
        <<: *common-vars
        cpuset: "6-9"
        image: vision-main:onboard-realsense
        container_name: onboard-realsense
        privileged: true
        volumes:
            - /dev:/dev
            - $LOCAL_WORKSPACE_FOLDER/config/dds-uri/cycloneDDS.xml:/tmp/cycloneDDS.xml
            - $LOCAL_WORKSPACE_FOLDER/packages/realsense-pkg:/home/onboard/vision-ws/src/realsense-ros
        device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
        command: >
            bash -ic "
            colcon build --packages-select realsense2_camera;
            source /home/realsense/vision-ws/install/local_setup.bash;
            ros2 launch realsense2_camera rs_launch.py
            "
        profiles: ['camera']

    avoidance:
        build:
            context: .
            target: avoidance 
            args:
                USER: avoidance
        <<: *common-vars
        cpuset: "10-15"
        image: vision-main:avoidance
        container_name: avoidance
        volumes:
            - $LOCAL_WORKSPACE_FOLDER/packages/avoidance-pkg:/home/avoidance/vision-ws/src/avoidance-ros
        # command: >
        #     bash -ic "
        #     colcon build --symlink-install --packages-select avoidance_ros;
        #     source /home/avoidance/vision-ws/install/local_setup.bash;
        #     ros2 launch avoidance_ros main.launch.py;
        #     "
        command: bash
        profiles: ['avoid']

    feedback:
        build:
            context: .
            target: feedback 
            args:
                USER: feedback
        <<: *common-vars
        image: vision-main:feedback
        container_name: feedback
        volumes:
            - $LOCAL_WORKSPACE_FOLDER/packages/feedback-pkg:/home/feedback/vision-ws/src/aruco-ros
        command: >
            bash -ic "
            colcon build --parallel-workers 6;
            source /home/feedback/vision-ws/install/local_setup.bash;
            ros2 launch aruco_ros single.launch.py;
            "
        profiles: ['feedback']