/vision/onboard_filter:
  ros__parameters:
    front_x_low: 0.16
    front_x_high: 0.5
    front_y_low: -0.5
    front_y_high: 0.5
    front_z_low: 0.015
    front_z_high: 0.5

    back_x_low: -0.5
    back_x_high: -0.16
    back_y_low: -0.5
    back_y_high: 0.5
    back_z_low: 0.015
    back_z_high: 0.5

    leaf_size: 0.01
    min_z: 0.3
    use_tf: true

/vision/velocity_publisher:
  ros__parameters:
    linear:
      x: 0.1
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0